### ISSUE TITLE
Project Identity

### ISSUE THREAD

**Issue by artingei** [GalliumOS/galliumos.org#1]
As I mentioned in IRC I tried to work out the visual identity of Gallium OS. 

The things which were done by @elioqoshi were definitely good but some kind of unfinished. I would like to stay with blue colors but in a stronger tonality so it doesn't seem to copy the colors of Chromium anymore and has an own identity regarding the colors. The logo was fine but not specified enough. One version was without partition of the four elements and the colored one merged all four together.

Hope you are fine with my suggestions and have the possibility to exchange it where it's already included  if it's "approved". 

![galliumos_logo](https://cloud.githubusercontent.com/assets/5765780/10995742/5a59f160-847f-11e5-9e94-fdbbc44ad2a2.png)

**Comment by ColtonDRG** [comment]
I like a lot of your changes, but I think we should have a quad color version of the main logo. Those look good too, but I would like to try a quad color logo

**Comment by ColtonDRG** [comment]
Wrong project. Post this in galliumos-distro

**Comment by elioqoshi** [comment]
Hi there,

The blue color is way too strong and not good on the eye, there was a reason I used lighter blue tones.
Also as Colton said, we should have a full color version (with 4 colored sides) also.
I also don't get why you say the logo was "unfinished" as I don't see a concrete reason for that, apart personal tastes.
