### ISSUE TITLE
Website colors

### ISSUE THREAD

**Issue by hugegreenbug** [GalliumOS/galliumos.org#13]
We need to standardize on the colors used for the website.

**Comment by hugegreenbug** [comment]
@elioqoshi and @artingei please decide in the colors to be used in the website.

**Comment by elioqoshi** [comment]
I generally think we should use colors taken from the logo. If we insist that the current color on the website is not fitting, I will look into adapt the logo too (I believe we should use a color from the logo, for obvious reasons).

**Comment by artingei** [comment]
Just tell me what to use (hex or rgb) @elioqoshi and I will adjust the  web styling.

**Comment by hugegreenbug** [comment]
@artingei, @elioqoshi said above to use the colors in the logo. I've attached and image with the hex colors
![logo-with-colors](https://cloud.githubusercontent.com/assets/1656137/11025076/0e1ca51e-8654-11e5-970b-60cf2115e666.png)

**Comment by reynhout** [comment]
closing for geriatricity
