### ISSUE TITLE
Header opacity

### ISSUE THREAD

**Issue by ColtonDRG** [GalliumOS/galliumos.org#19]
This is the issue version of #18, which was a pr... for some reason...

Yes, it initially had some opacity, but I took it away because I thought it looked odd when I scrolled down.

The way I see it, there are ~~four~~ five ways to move forward
1: leave it the way it is
2: add opacity
3: make the header opaque, but make it a different colour from the background so it doesn't look weird
4: add some sort of gradient (I'm not sure if this would look good or not.)
5: make it transparent, but add some fading opacity to a different colour when you scroll down

**Comment by futurecookieman** [comment]
I really like the idea of adding some fading opacity when scrolling. We could make it look good with a gray, or a variety of blue. Either way it would give the best look.

**Comment by reynhout** [comment]
closed for inactivity
