### ISSUE TITLE
Video embed

### ISSUE THREAD

**Issue by artingei** [GalliumOS/galliumos.org#4]
We could embed a webm or gif video to show some animations on the screen of the laptop on the main page. No need to be finished for beta, but maybe for RC1?

**Comment by hugegreenbug** [comment]
Sounds cool. What would the animation show?

**Comment by artingei** [comment]
Some interface elements and the general look & feel (file manager, browser, settings).

**Comment by hugegreenbug** [comment]
I would prefer to somehow show the replacement and advantages over ChromeOS in the animation. We aren't necessarily going to win over users with desktop.

**Comment by ColtonDRG** [comment]
Many users have requested more screenshots in IRC and reddit. I think an animation showing desktop elements is a great idea.

**Comment by artingei** [comment]
I will try to get it done on sunday.

**Comment by reynhout** [comment]
I made a short video that shows the basic UI and installed software. It's several weeks old now, but is viewable at https://galliumos.org/video1.mp4

**Comment by reynhout** [comment]
closed as abandoned
